# Generated by Django 5.2.14 on 2026-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(blank=True, default='/static/images/recipe-default.svg', max_length=500),
        ),
    ]
